"""empty message

Revision ID: 8a940437f5f5
Revises: 8e82d6f90d17
Create Date: 2019-12-28 11:07:03.069105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a940437f5f5'
down_revision = '8e82d6f90d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_game', sa.Column('ranked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_game', 'ranked')
    # ### end Alembic commands ###
